name: CI Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Login Dockerhub
      env:
        DOCKERHUB_USERNAME: ${{secrets.DOCKER_USERNAME}}
        DOCKER_PASS: ${{secrets.DOCKER_PASS}}
      run: docker login -u $DOCKERHUB_USERNAME -p $DOCKER_PASS
    - name: Build the Docker image
      run: docker build -t anitbishwas/exotel-ivr .
    - name: Push to Dockerhub
      run: docker push anitbishwas/exotel-ivr:latest